apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
    manifests: 
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: lantianyou/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: lantianyou/comments
      context: comments
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: lantianyou/event-bus
      context: event-bus
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: lantianyou/moderation
      context: moderation
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: lantianyou/posts
      context: posts
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: lantianyou/query
      context: query
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .